package com.example.t1.domain.model.behaviour

enum class AppCategory {
    SOCIAL, ENTERTAINMENT, PRODUCTIVITY, EDUCATION,
    COMMUNICATION, FINANCE, HEALTH, UTILITIES,
    SHOPPING, NAVIGATION, DEVELOPMENT, MEDIA,
    PHOTOGRAPHY, SYSTEM, OTHER
}
